name: Daily Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC 시간 기준)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main  # main 브랜치 동기화
        fetch-depth: 0

    - name: Sync Fork
      run: |
        git config --global user.email "ddoeatddoeat@gmail.com"
        git config --global user.name "ddoeat"
        git remote add upstream https://github.com/depromeet/ddoeat_client.git
        git fetch upstream
        git merge upstream/main
        git push
